# Generated by Django 4.1.3 on 2024-02-06 05:45

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Gallery.models.image_upload_path, verbose_name='Image Album')),
            ],
            options={
                'verbose_name_plural': '1. Images',
            },
        ),
    ]
