# Generated by Django 5.0.1 on 2024-02-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin_teacher_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4. Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '3. Teacher'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
    ]
